import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './theme-provider';
import { Toaster } from 'sonner';
import { ClerkProvider } from '@clerk/nextjs';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Salex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable}  antialiased`}
        suppressHydrationWarning
      >
        <ClerkProvider>
          <Toaster richColors />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}{' '}
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
