import { SaleType } from './types';
import { nanoid } from 'nanoid';

export const salesData: SaleType[] = [
  {
    id: nanoid(),
    customerName: 'Acme Corp',
    dealValue: '₹20,000',
    status: 'In Progress',
    contactDate: '2024-03-05',
    salesperson: 'Charlie Davis',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Tech Solutions',
    dealValue: '₹5,750',
    status: 'Closed Lost',
    contactDate: '2024-02-28',
    salesperson: 'Emily White',
    priority: 'Low',
  },
  {
    id: nanoid(),
    customerName: 'Global Inc',
    dealValue: '₹18,400',
    status: 'Closed Won',
    contactDate: '2024-01-30',
    salesperson: 'Frank Lee',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Creative Minds',
    dealValue: '₹3,200',
    status: 'In Progress',
    contactDate: '2024-03-12',
    salesperson: 'Bob Johnson',
    priority: 'Low',
  },
  {
    id: nanoid(),
    customerName: 'NextGen Solutions',
    dealValue: '₹9,500',
    status: 'Closed Won',
    contactDate: '2024-02-07',
    salesperson: 'Alice Brown',
    priority: 'Medium',
  },
  {
    id: nanoid(),
    customerName: 'Sunrise Ventures',
    dealValue: '₹4,100',
    status: 'In Progress',
    contactDate: '2024-02-20',
    salesperson: 'Charlie Davis',
    priority: 'Low',
  },
  {
    id: nanoid(),
    customerName: 'PixelWorks',
    dealValue: '₹7,800',
    status: 'Closed Won',
    contactDate: '2024-01-18',
    salesperson: 'Emily White',
    priority: 'Medium',
  },
  {
    id: nanoid(),
    customerName: 'Innovate Labs',
    dealValue: '₹15,600',
    status: 'Negotiation',
    contactDate: '2024-03-22',
    salesperson: 'Frank Lee',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Alpha Co',
    dealValue: '₹11,200',
    status: 'In Progress',
    contactDate: '2024-02-25',
    salesperson: 'Bob Johnson',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Beta Tech',
    dealValue: '₹6,400',
    status: 'Closed Won',
    contactDate: '2024-01-27',
    salesperson: 'Alice Brown',
    priority: 'Medium',
  },
  {
    id: nanoid(),
    customerName: 'Omega Solutions',
    dealValue: '₹14,300',
    status: 'Closed Won',
    contactDate: '2024-03-15',
    salesperson: 'Charlie Davis',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Zeta Group',
    dealValue: '₹2,900',
    status: 'In Progress',
    contactDate: '2024-02-11',
    salesperson: 'Emily White',
    priority: 'Low',
  },
  {
    id: nanoid(),
    customerName: 'Delta Dynamics',
    dealValue: '₹19,800',
    status: 'Closed Won',
    contactDate: '2024-03-08',
    salesperson: 'Frank Lee',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Fusion Inc',
    dealValue: '₹8,900',
    status: 'Closed Lost',
    contactDate: '2024-01-22',
    salesperson: 'Bob Johnson',
    priority: 'Medium',
  },
  {
    id: nanoid(),
    customerName: 'Vortex Labs',
    dealValue: '₹13,500',
    status: 'In Progress',
    contactDate: '2024-02-05',
    salesperson: 'Alice Brown',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Echo Enterprises',
    dealValue: '₹10,700',
    status: 'Closed Won',
    contactDate: '2024-03-02',
    salesperson: 'Charlie Davis',
    priority: 'Medium',
  },
  {
    id: nanoid(),
    customerName: 'Nova Tech',
    dealValue: '₹4,800',
    status: 'Closed Lost',
    contactDate: '2024-01-14',
    salesperson: 'Emily White',
    priority: 'Low',
  },
  {
    id: nanoid(),
    customerName: 'Apex Corp',
    dealValue: '₹16,200',
    status: 'In Progress',
    contactDate: '2024-02-18',
    salesperson: 'Frank Lee',
    priority: 'High',
  },
  {
    id: nanoid(),
    customerName: 'Quantum Solutions',
    dealValue: '₹7,400',
    status: 'Closed Won',
    contactDate: '2024-03-25',
    salesperson: 'Bob Johnson',
    priority: 'Medium',
  },
];
